// ------------------------------------------------------------
// 全站文案与数据。中/英双语，结构一一对应。
// 组件里统一用 content[lang].xxx 取数据，新增文案时两边都要补。
// ------------------------------------------------------------

export const social = {
  instagram: 'https://www.instagram.com/lion_eki1113/',
  youtube: 'https://www.youtube.com/@LionLeon-i9l',
  paypal: 'https://www.paypal.com/paypalme/LeonYi138',
  email: 'lionekikun@gmail.com',
}

export const nav = {
  zh: [
    { label: '关于', href: 'index.html#profile' },
    { label: '作品', href: 'portfolio.html' },
    { label: '打赏', href: 'index.html#support' },
    { label: '联系', href: 'index.html#contact' },
  ],
  en: [
    { label: 'Profile', href: 'index.html#profile' },
    { label: 'Work', href: 'portfolio.html' },
    { label: 'Support', href: 'index.html#support' },
    { label: 'Contact', href: 'index.html#contact' },
  ],
}

export const content = {
  zh: {
    siteName: 'LEON YI',
    navContactBtn: '联系我',
    hero: {
      roles: ['视觉设计师', 'CG 艺术家', '影像作者', '艺术家'],
      titleTop: 'LEON',
      titleBottom: 'YI',
      tagline: ['视觉设计 · CG · 影像', '看画面就够了'],
      scroll: '向下滚动 · SCROLL',
    },
    profile: {
      eyebrow: '01 / PROFILE',
      location: '全球 / 东京',
      availability: '接受合作 · OPEN FOR PROJECTS',
      tabAbout: '01 / ABOUT',
      tabCv: '02 / CV',
      aboutTitle: '关于我',
      aboutParagraphs: [
        '我是一名来自中国沿海的视觉设计师、CG 艺术家与影像作者，创作横跨平面与影像。',
        '我是一个朋克中的浪漫主义者，在极端的视角下寻找足够锋利的表达方式。',
        '比起艺术，我更热爱地下文化对于表达的态度。',
        '我目标成为一个通才，不受限地提升自己各方面技能和素养。',
        '目前在日本进修影像专业，同时持续接一些商业与独立项目的合作，也保持着每天制作一个视觉作品的习惯。',
      ],
      facts: [
        { label: '身份', value: '视觉设计师 / CG / 影像 / 艺术家' },
        { label: '所在地', value: '全球 / 东京' },
        { label: '状态', value: '接受商业合作与展览邀约' },
      ],
      contacts: [
        { label: 'EMAIL', value: 'lionekikun@gmail.com', href: 'mailto:lionekikun@gmail.com', icon: 'mail' },
        { label: 'INSTAGRAM', value: '@lion_eki1113', href: social.instagram, icon: 'instagram' },
        { label: 'YOUTUBE', value: '@LionLeon-i9l', href: social.youtube, icon: 'youtube' },
      ],
      cvTitle: '履历',
      cvItems: [
        { year: '2020', desc: '毕业于中国美术学院附中' },
        {
          year: '2026',
          desc: '毕业于京都精华大学媒体创作学院',
          href: 'https://www.kyoto-seika.ac.jp/eng/academics/mediacreation/',
        },
        {
          year: '进行中',
          desc: '现于武藏野美术大学映像学科大学院进修',
          href: 'https://www.musabi.ac.jp/english/course/undergraduate-ctsi/ias/',
        },
      ],
    },
    work: {
      eyebrow: '02 / SELECTED WORK',
      title: '作品',
      desc: '从参与的主要项目，到从 2026 年 7 月开始坚持的每日一图，记录我看待世界的方式。',
      cta: '查看全部作品',
      tabVideo: '影像',
      tabStatic: '平面',
      tabGame: '互动',
      tabMusic: '声音',
      tabPainting: '绘画',
    },
    support: {
      eyebrow: '03 / SUPPORT',
      titleTop: '请我',
      titleBottom: '喝一杯',
      body: '喜欢我的作品的话，可以请我喝一杯，支持我继续做下去。',
      paypalLabel: '去 PayPal 支持',
    },
    contact: {
      eyebrow: '04 / CONTACT',
      titleTop: "LET'S",
      titleBottom: 'TALK',
      subtitle: '有项目想聊，或者只是单纯想聊聊创作与生活，都欢迎写信给我。',
      inquiryBtn: '发送项目咨询 →',
      emailLabel: '或者直接发邮件到',
      back: '↑ 回到顶部 / BACK TO TOP',
    },
    portfolioPage: {
      eyebrow: 'WORK',
      title: '作品集',
      back: '← 返回首页',
      mainLabel: '主要作品',
      mainDesc: '这是我参与的主要项目。',
      dailyLabel: '每日作品',
      dailyDesc: '从 2026 年 7 月开始，我坚持每天制作一个视觉，这里放的是精选。',
    },
    contactPage: {
      eyebrow: 'CONTACT',
      title: '项目咨询',
      desc: '填写下面的表单，我会尽快回复你，也可以直接发邮件到 lionekikun@gmail.com。',
      emailLabel: '你的邮箱',
      emailPlaceholder: 'name@example.com',
      messageLabel: '咨询内容',
      messagePlaceholder: '介绍一下你的项目、预算与时间线……',
      submit: '发送 →',
      back: '← 返回首页',
      note: '首次发送后，请到 lionekikun@gmail.com 的收件箱确认一次激活邮件，之后的消息会正常送达。',
    },
    workPage: {
      back: '← 返回作品集',
      notFound: '没有找到这件作品。',
      backHome: '← 返回作品集',
    },
  },

  en: {
    siteName: 'LEON YI',
    navContactBtn: 'Contact',
    hero: {
      roles: ['Visual Designer', 'CG Artist', 'Filmmaker', 'Artist'],
      titleTop: 'LEON',
      titleBottom: 'YI',
      tagline: ['Visual design · CG · Film', 'The work speaks for itself'],
      scroll: 'SCROLL DOWN',
    },
    profile: {
      eyebrow: '01 / PROFILE',
      location: 'Global / Tokyo',
      availability: 'OPEN FOR PROJECTS',
      tabAbout: '01 / ABOUT',
      tabCv: '02 / CV',
      aboutTitle: 'About',
      aboutParagraphs: [
        "I'm a visual designer, CG artist and filmmaker from coastal China, working across print and film.",
        "I'm a romantic within punk — chasing a sharp enough way to say things from an extreme angle.",
        "More than art itself, what I love is underground culture's attitude toward expression.",
        "My goal is to become a generalist, growing my skills and taste without limits.",
        "I'm currently studying film in Japan, taking on commercial and independent projects along the way, and keeping a daily habit of making one visual.",
      ],
      facts: [
        { label: 'Role', value: 'Visual Designer / CG / Film / Artist' },
        { label: 'Based in', value: 'Global / Tokyo' },
        { label: 'Status', value: 'Open for commissions & exhibitions' },
      ],
      contacts: [
        { label: 'EMAIL', value: 'lionekikun@gmail.com', href: 'mailto:lionekikun@gmail.com', icon: 'mail' },
        { label: 'INSTAGRAM', value: '@lion_eki1113', href: social.instagram, icon: 'instagram' },
        { label: 'YOUTUBE', value: '@LionLeon-i9l', href: social.youtube, icon: 'youtube' },
      ],
      cvTitle: 'CV',
      cvItems: [
        { year: '2020', desc: 'Graduated from the Middle School Affiliated to China Academy of Art' },
        {
          year: '2026',
          desc: 'Graduated from Kyoto Seika University, Faculty of Media Creation',
          href: 'https://www.kyoto-seika.ac.jp/eng/academics/mediacreation/',
        },
        {
          year: 'Ongoing',
          desc: 'Graduate studies in the Department of Imaging Arts and Sciences at Musashino Art University',
          href: 'https://www.musabi.ac.jp/english/course/undergraduate-ctsi/ias/',
        },
      ],
    },
    work: {
      eyebrow: '02 / SELECTED WORK',
      title: 'Work',
      desc: 'From the main projects I take on, to a daily visual practice running since July 2026 — a record of how I see the world.',
      cta: 'View all work',
      tabVideo: 'Film',
      tabStatic: 'Print',
      tabGame: 'Interactive',
      tabMusic: 'Sound',
      tabPainting: 'Painting',
    },
    support: {
      eyebrow: '03 / SUPPORT',
      titleTop: 'Buy me',
      titleBottom: 'a drink',
      body: "If you like what I make, a small tip helps me keep making it.",
      paypalLabel: 'Support via PayPal',
    },
    contact: {
      eyebrow: '04 / CONTACT',
      titleTop: "LET'S",
      titleBottom: 'TALK',
      subtitle: "Got a project in mind, or just want to talk about art and life — I'd love to hear from you.",
      inquiryBtn: 'Send a project inquiry →',
      emailLabel: 'Or email directly at',
      back: '↑ BACK TO TOP',
    },
    portfolioPage: {
      eyebrow: 'WORK',
      title: 'Portfolio',
      back: '← Back home',
      mainLabel: 'Main works',
      mainDesc: "These are the primary projects I've worked on.",
      dailyLabel: 'Daily works',
      dailyDesc: "Since July 2026, I've been making one visual every day — here's a curated selection.",
    },
    contactPage: {
      eyebrow: 'CONTACT',
      title: 'Project inquiry',
      desc: "Fill in the form below and I'll get back to you soon — or email me directly at lionekikun@gmail.com.",
      emailLabel: 'Your email',
      emailPlaceholder: 'name@example.com',
      messageLabel: 'Message',
      messagePlaceholder: 'Tell me about your project, budget and timeline...',
      submit: 'Send →',
      back: '← Back home',
      note: 'After the first submission, please confirm the activation email in the lionekikun@gmail.com inbox — messages after that will be delivered normally.',
    },
    workPage: {
      back: '← Back to work',
      notFound: 'Could not find this piece.',
      backHome: '← Back to work',
    },
  },
}

export const mainWorks = [
  {
    id: '01',
    year: '2026',
    type: 'video',
    titleZh: '现场视觉 - 自愿',
    titleEn: 'Live Visuals — Voluntary',
    categoryZh: 'VJ 现场影像',
    categoryEn: 'Live VJ Visuals',
    image: '/works/yaoya-vj-web.jpg',
    descZh: '为「咬牙 Yaoya」乐队现场演出创作的 VJ 视觉。这里可以补充更多创作细节——用了什么软件/引擎、现场氛围、创作思路等。',
    descEn: 'Live VJ visuals made for a Yaoya show. More on the process, tools and the night itself can go here.',
  },
  {
    id: '02',
    year: '2024',
    type: 'video',
    titleZh: 'The Forest',
    titleEn: 'The Forest',
    categoryZh: '艺术影像',
    categoryEn: 'Art Film',
    image: '/works/the-forest-web.jpg',
    descZh: '个人艺术影像作品。这里可以补充创作背景、制作方式、想表达的主题等。',
    descEn: 'A personal art film. Background on the concept, process and themes can go here.',
  },
  {
    id: '03',
    year: '2025',
    type: 'video',
    titleZh: 'The Shamans',
    titleEn: 'The Shamans',
    categoryZh: '艺术影像',
    categoryEn: 'Art Film',
    image: '/works/the-shamans-web.jpg',
    descZh: '个人艺术影像作品。这里可以补充创作背景、制作方式、想表达的主题等。',
    descEn: 'A personal art film. Background on the concept, process and themes can go here.',
  },
  {
    id: '04',
    year: '2025',
    type: 'video',
    titleZh: 'The Forsaken Ones',
    titleEn: 'The Forsaken Ones',
    categoryZh: '艺术影像',
    categoryEn: 'Art Film',
    duration: '3:11',
    image: '/works/the-forsaken-ones-web.jpg',
    descZh: '个人艺术影像作品，时长 3 分 11 秒。这里可以补充创作背景、灵感来源、制作过程等。',
    descEn: 'A personal art film, 3:11 in length. Background on the concept and process can go here.',
  },
  {
    id: '05',
    year: '2023',
    type: 'static',
    titleZh: '静帧习作',
    titleEn: 'Still Study',
    categoryZh: '摄影',
    categoryEn: 'Photography',
  },
  {
    id: '06',
    year: '2023',
    type: 'video',
    titleZh: '动态实验',
    titleEn: 'Motion Study',
    categoryZh: 'CG / 动画',
    categoryEn: 'CG / Animation',
  },
  {
    id: '07',
    year: '2022',
    type: 'static',
    titleZh: '视觉习作',
    titleEn: 'Visual Study',
    categoryZh: '视觉设计',
    categoryEn: 'Visual Design',
  },
  {
    id: '08',
    year: '2026',
    type: 'game',
    titleZh: '互动装置习作',
    titleEn: 'Interactive Study',
    categoryZh: '游戏 / 互动影像',
    categoryEn: 'Game / Interactive',
  },
  {
    id: '09',
    year: '2026',
    type: 'music',
    titleZh: '声音实验',
    titleEn: 'Sound Study',
    categoryZh: '音乐 / 声音',
    categoryEn: 'Music / Sound',
  },
  {
    id: '10',
    year: '2026',
    type: 'painting',
    titleZh: '手绘练习',
    titleEn: 'Drawing Study',
    categoryZh: '绘画',
    categoryEn: 'Painting',
  },
]

// 每日作品是精选，不是每天都传，这里先放 8 个占位，替换成真实的就行
const dailyDates = ['07.02', '07.09', '07.15', '07.23', '08.01', '08.06', '08.14', '08.20']
export const dailyWorks = dailyDates.map((d, i) => ({
  id: String(i + 1).padStart(3, '0'),
  date: `2026.${d}`,
}))
